---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 03.04.2023 18:58
---


require 'strict'.on()

box.cfg {
    listen = '3401',

}
box.once("init", function()

    -- auth testing: access control
    box.schema.user.create('test', { password = 'test' })
    box.schema.user.grant('test', 'execute', 'universe')

end)

local log = require 'log'
function push_messages(messages)

    log.info(messages)
    log.info(messages.Action3)

    log.info(messages[2])

    local m = { }
   -- table.insert(m, messages[1])
  --  table.insert(m, messages[2])

    return messages

end